name: Weekly Research Report

on:
  schedule:
    # 毎週月曜日 08:00 JST (= 日曜日 23:00 UTC)
    - cron: '0 23 * * 0'
  
  # 手動実行も可能にする
  workflow_dispatch:

jobs:
  generate-report:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          pip install langchain-google-genai langchain-tavily langgraph
      
      - name: Generate weekly report
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          TAVILY_API_KEY: ${{ secrets.TAVILY_API_KEY }}
        run: |
          python weekly_research.py
      
      - name: Commit and push report
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add reports/
          git diff --quiet && git diff --staged --quiet || (git commit -m "Add weekly report $(date +'%Y%m%d')" && git push)