name: Weekly Research Report

on:
  schedule:
    - cron: '0 23 * * 0'
  workflow_dispatch:

# ← この部分を追加
permissions:
  contents: write

jobs:
  generate-report:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install langchain-google-genai langchain-tavily langgraph
      
      - name: Generate weekly report
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          TAVILY_API_KEY: ${{ secrets.TAVILY_API_KEY }}
        run: |
          python weekly_research.py
      
      - name: Commit and push report
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add reports/
          git diff --quiet && git diff --staged --quiet || (git commit -m "Add weekly report $(date +'%Y%m%d')" && git push)